### ISSUE TITLE
解决io.netty.util.IllegalReferenceCountException: refCnt: 0问题。

### ISSUE THREAD

**Issue by SuperWuYou** [daoshenzzg/socket-mqtt#10]
**因为netty4之后BytBuf加入了计数器概念**
**我们在创建Server的时候开启了异步执行，如下图：**
![image](https://user-images.githubusercontent.com/54934275/110742488-6ad21400-8271-11eb-984e-b7bc5fbb3fbf.png)

**这个时候呢，在代码执行到ServerDispatchHandler.channelRead()这个方法时，里面有这么一句代码** **eventDispatcher.dispatchMessageEvent(ctx, channel, msg);**
![image](https://user-images.githubusercontent.com/54934275/110743136-838ef980-8272-11eb-9f9c-4f0c4c4375f3.png)
**这句代码的实现是这样的：**
![image](https://user-images.githubusercontent.com/54934275/110743252-b3d69800-8272-11eb-859e-283777f0aa4f.png)
**因为是异步的情况，在我们还没有读取ByteBuf数据时就已经先执行了如下图这句代码：**
![image](https://user-images.githubusercontent.com/54934275/110743530-23e51e00-8273-11eb-8a2a-13b16cb820fd.png)
**这时候ByteBuf已经被释放了，所以我们抛出了io.netty.util.IllegalReferenceCountException: refCnt: 0异常。**
**解决方法：**
**1. 改为同步执行**
![image](https://user-images.githubusercontent.com/54934275/110743680-673f8c80-8273-11eb-9d7b-7db4009d56a1.png)
**2. 修改作者代码**
![image](https://user-images.githubusercontent.com/54934275/110743836-a968ce00-8273-11eb-8bf4-2f9e7358ad2c.png)

**Comment by daoshenzzg** [comment]
问题确实存在，按照你的方式解决啦。
