### ISSUE TITLE
日志配置文件及位置

### ISSUE THREAD

**Issue by boluofan** [daoshenzzg/socket-mqtt#11]
请问下 这个项目的日志是打印在哪里呢？我想测试，但没找到打印日志和日志配置文件

**Comment by daoshenzzg** [comment]
日志默认打到控制台了，可以自己配置的。

**Comment by boluofan** [comment]
好的 看到了 谢谢！还有个事情请教下 
 现在项目中的普通模式也是可以实现socket长连接吧  是需要自己使用心跳包吗？有没有测试代码

**Comment by boluofan** [comment]
好的 看到了 谢谢！还有个事情请教下 
 现在项目中的普通模式也是可以实现socket长连接吧  是需要自己使用心跳包吗？有没有测试代码吗？
