### ISSUE TITLE
生产项目应用过吗

### ISSUE THREAD

**Issue by hexl21** [daoshenzzg/socket-mqtt#12]
生产项目应用过吗

**Comment by daoshenzzg** [comment]
是的，应用到了生产项目，由于技术选型我们应用的自定义消息协议。需要说明的是：我们内部基础框架是`socket-mqtt`的阉割版本，比如去掉了一些不需要的协议实现。`socket-mqtt`大体框架是没有问题的，经过了实战考验。如果直接把`socket-mqtt`打成jar直接引用也是没有问题的，但建议还是要做相关的验证和测试。
