### ISSUE TITLE
请问下我想做消息持久化，代码是不是应该写在com.yb.socket.listener.DefaultMqttMessageEventListener#publish

### ISSUE THREAD

**Issue by liu-xinhui** [daoshenzzg/socket-mqtt#13]
是不是写在下图的位置
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/7698511/174956502-87008d37-ff72-4a8a-bd27-e37faddd1b57.png">

**Comment by daoshenzzg** [comment]
是的。EchoMessageEventListener 继承 DefaultMqttMessageEventListener 覆写 publish 方法，表示接受来自客户端的消息，在这个位置进行持久化即可。
