### ISSUE TITLE
普通的client连接后关闭出现内存泄露

### ISSUE THREAD

**Issue by 244175455** [daoshenzzg/socket-mqtt#14]
@Service("ClientServiceImpl")
public class ClientServiceImpl implements IClientService {

    public String messageSend(String ip,Integer port,String message){
        MsgDecoder decoder = new MsgDecoder();
        MsgEncoder encoder = new MsgEncoder();
        Client client=new Client();
        client.setIp(ip);
        client.setPort(port);
        client.setConnectTimeout(10000);
        client.setCheckHeartbeat(false);
        client.addChannelHandler("decoder", decoder);
        client.addChannelHandler("encoder", encoder);
        client.connect();
        Request request = new Request();
        request.setSequence(1);
        request.setMessage(message);
        Response response=null;
        try {
            response = client.sendWithSync(request, 30000);
            client.shutdown();
            return response.getResult().toString();
        }catch (Exception e){
            client.shutdown();
            log.error("消息发送失败:{},指令:{}",e.getMessage(),message);
            throw new RestfulEx(RestfulStatus.H500,"消息发送失败!");
        }finally {
            //强制回收内存
            client=null;
            decoder=null;
            encoder=null;
            request=null;
            response=null;
            System.gc();
        }
    }

}

**Comment by 244175455** [comment]
<img width="860" alt="Snipaste_2022-08-01_13-56-12" src="https://user-images.githubusercontent.com/41325566/182083961-6a04fb53-7085-413f-a47d-b5e3e5b631e9.png">
调用后这些对象一直无法回收

**Comment by daoshenzzg** [comment]
强制调用System.gc()并不能保证立即回收所有的对象。垃圾回收是由垃圾回收器自动管理的，它会根据一些算法和条件来决定何时回收对象。因此，虽然你已经将对象设置为null并调用了System.gc()，但并不能保证立即回收这些对象。
