### ISSUE TITLE
MQTT发布消息出现异常

### ISSUE THREAD

**Issue by jeffrey-alan** [daoshenzzg/socket-mqtt#2]
// Server端默认使用业务处理线程池。
this.openExecutor = true;

在这种情况下，使用MQTT协议发布消息的时候，dispatchMessageEvent 的时候会出现传值异常，无法解析内容部分，引发IllegalReferenceCountException异常

**Comment by daoshenzzg** [comment]
你好，能贴下相关代码吗？我这里没有复现。

**Comment by jeffrey-alan** [comment]
服务类：com.yb.socket.service.mqtt.MqttServerTest客户端工具：Eclipse Paho MQT Utility不是什么大问题，msg在进入线程的时候，传的值出了异常




------------------ 原始邮件 ------------------
发件人: "doashenzzg"<notifications@github.com>; 
发送时间: 2019年7月25日(星期四) 上午9:17
收件人: "daoshenzzg/socket-mqtt"<socket-mqtt@noreply.github.com>; 
抄送: ""<9041721@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [daoshenzzg/socket-mqtt] MQTT发布消息出现异常 (#2)




你好，能贴下相关代码吗？我这里没有复现。

**Comment by 765947965** [comment]
你好  在获取值的时候抛出了异常
![image](https://user-images.githubusercontent.com/15795208/62431474-5dca7600-b75a-11e9-8446-0452ddd309a6.png)
![image](https://user-images.githubusercontent.com/15795208/62431493-86527000-b75a-11e9-9840-50f6de6d1424.png)

**Comment by NVCNV** [comment]
遇到同样的问题  解决了么？

**Comment by daoshenzzg** [comment]
同 #10
