### ISSUE TITLE
在解析消息内容的时候出现异常

### ISSUE THREAD

**Issue by 765947965** [daoshenzzg/socket-mqtt#3]
![image](https://user-images.githubusercontent.com/15795208/62431555-f7922300-b75a-11e9-8edb-6b9b8dff49aa.png)
![image](https://user-images.githubusercontent.com/15795208/62431562-04af1200-b75b-11e9-9205-0efdbe3f4ed1.png)

**Comment by lnzhao1** [comment]
![1583238796](https://user-images.githubusercontent.com/26715467/75776074-38542800-5d8e-11ea-862d-bdf491126cad.jpg)
maybe work

**Comment by daoshenzzg** [comment]
同 #10
