### ISSUE TITLE
心跳开启时，第二个tcp客户端连接不上

### ISSUE THREAD

**Issue by suzi221** [daoshenzzg/socket-mqtt#4]
![image](https://user-images.githubusercontent.com/38639257/70970782-3efdc800-20da-11ea-9d8d-e2a77679a132.png)
后面新建了一个类ServerIdleStateHandler并继承IdleStateHandler，添加注解@ChannelHandler.Sharable
，在com/yb/socket/service/server/Server.java中，将原来的IdleStateHandler换成ServerIdleStateHandler才解决。
问题二：注册中心这个怎么使用呢？有没有交流群或者文档之类的，是用tcp客户端连接注册注册中心吗？

**Comment by daoshenzzg** [comment]
你好，
问题一：我按照你的方式试了一下，并没有出现第二个连接不上的情况，请问你是怎么连接的呢？

问题二：暂时没有交流群、文档之类的，目前工作比较忙没太多精力来完善。这个项目仅供大家参考，一起学习。

本地调试截图：
![image](https://user-images.githubusercontent.com/7531802/71453558-bc09fb00-27c6-11ea-8045-fd6cc1cf5889.png)
