### ISSUE TITLE
这个项目是不是不完善

### ISSUE THREAD

**Issue by waytai** [daoshenzzg/socket-mqtt#6]
我用mqttfx测试了一下，除了连接，其他的发送，接收都不走
if (msg instanceof MqttMessage) {
            MqttMessage message = (MqttMessage) msg;
            MqttMessageType messageType = message.fixedHeader().messageType();
            switch (messageType) {
                case CONNECT:
                    this.connect(channel, (MqttConnectMessage) message);
                    break;
                case PUBLISH:
                    this.publish(channel, (MqttPublishMessage) message);
                    break;
                case SUBSCRIBE:
                    this.subscribe(channel, (MqttSubscribeMessage) message);
                    break;
                case UNSUBSCRIBE:
                    this.unSubscribe(channel, (MqttUnsubscribeMessage) message);
                    break;
                case PINGREQ:
                    this.pingReq(channel, message);
                    break;
                case DISCONNECT:
                    this.disConnect(channel, message);
                    break;
                default:
                    if (logger.isDebugEnabled()) {
                        logger.debug("Nonsupport server message  type of '{}'.", messageType);
                    }
                    break;
            }
        }
这段代码

**Comment by daoshenzzg** [comment]
是的，需要自己来实现。在test模块有测试用例代码，需要哪个事件实现哪个即可。
